Fixed issue with /system mount checks + write protect wlan_mac.bin on install
Change-Id: I072b877631f9f3bed9920cfb3b2e07d74b1f8658

diff --git a/hybris-installer/META-INF/com/google/android/update-binary b/hybris-installer/META-INF/com/google/android/update-binary
--- a/hybris-installer/META-INF/com/google/android/update-binary
+++ b/hybris-installer/META-INF/com/google/android/update-binary
@@ -61,9 +61,10 @@ invalid_device && CURRENT_DEVICE=`getprop ro.build.product`
 mount | grep -q "/data.*ext4" || abort 3 "Data is NOT formatted as ext4; check out 'Wipe > Advanced' from TWRP!"
 
 # Treble
-if [ -d /system_root ] && [ "$(ls -A /system_root)" -eq 1 ] ; then # If /system_root exists and is empty
-	log "Device is system-as-root but /system_root is mounted to /system, fixing"
+if [ -d /system_root ]; then # If /system_root exists and is empty
+	log "Device is system-as-root, ensuring /system_root and /system are mounted correctly"
 	umount /system
+	umount /system_root
 	mount /dev/block/bootdevice/by-name/system /system_root || abort 99 "Failed to mount system to /system_root"
 	mount -o bind /system_root /system || abort 98 "Failed to bind mount /system_root/system to /system"
 	log "Successfully fixed /system mountpoint, toybox should work properly now..."
@@ -147,9 +148,12 @@ rm $ARCHIVE
 log "Cloning /persist from Android to prevent issues with WiFi when dual booting"
 mkdir /persist
 mount /dev/block/bootdevice/by-name/persist /persist
+mkdir -p /data/.stowaways/sailfishos/mnt/vendor/persist
 cp -r /persist/* $ROOT/mnt/vendor/persist/
 log "Disabling /mnt/vendor/persist mount point"
 ln -s /dev/null $ROOT/etc/systemd/system/mnt-vendor-persist.mount
+log "making wlan_mac.bin read only. To stop android services from clearing it"
+chmod 044 /data/.stowaways/sailfishos/mnt/vendor/persist/wlan_mac.bin
 
 log "Fixing up init scripts..."
 sed -e "/extraenv/s/^/#/g" -e "/import \/init.\${ro.hardware}.rc/s/^/#/" -e "/ro.zygote/s/^/#/g" -e "/start update_verifier/s/^/#/g" \
@@ -170,7 +174,7 @@ elif [ -f /tmp/droid-boot.img ]; then
 fi
 
 log "Writing hybris-boot image..."
-dd if=$ROOT/boot/hybris-boot.img of=/dev/block/bootdevice/by-name/boot || abort 11 "Couldn't write Hybris boot image!"
+dd if=$ROOT/boot/hybris-boot.img of=/dev/block/bootdevice/by-name/boot_a || abort 11 "Couldn't write Hybris boot image!"
 
 # <<< Script <<<
 
